config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from main.web import urls as home_urls

urlpatterns = [
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^', include(home_urls, namespace="web", app_name="web")),
]

main/web/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
	url(r'^account/logout/$', logout_view, name="logout_view"),
	url(r'^account/login/$', login_view, name="login_view"),
	url(r'^trade_prices_check/$', trade_prices_check, name="trade_prices_check"),
	url(r"^$", view=home_view, name='home_view'),

]

main/web/views/home.py
# -*- encoding: utf-8 -*-
from django.utils.translation import ugettext as _
from django.shortcuts import HttpResponseRedirect, render, redirect, HttpResponse
from django.core.urlresolvers import reverse

from main.core.utils import is_json
from main.core.gw import CoinMarketCap
from operator import is_not
from functools import partial
import re, json

def home_view(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse("web:login_view"))
	return render(request, "web/content/home.html", {})

def trade_prices_check(request):
	args = "{}"
	cmc = CoinMarketCap(request=request, DEBUG=False)
	response = cmc.ticker()
	if is_json(response):
			args = response
			search = request.POST.get("search")
			if search:
				def searchinlist(dt):
					matched = False
					pattern = re.compile(re.escape(search))
					if re.search(pattern, "{}".format(dt.get("name"))) or re.search(pattern, "{}".format(dt.get("id"))):
						matched = True
					return dt if matched else None
				args = json.dumps(list(filter(partial(is_not, None), map(searchinlist, json.loads(args)))))
	return HttpResponse(args, content_type="application/json")

def trade_prices_check_detail(request, cid):
	args = {}
	

main/web/templates/web/SAMPLE.html
{% extends "web/base.html" %}
{% load i18n staticfiles %}
{% block title %}{% trans "Home" %}{% endblock title %}
{% block extracss %}{% endblock extracss %}
{% block content %}
	<div class="container">
		HOME
	</div>
{% endblock content %}
{% block extrajs %}{% endblock extrajs %}

main/web/templates/web/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/ico" href="{% if CONFIG.favicon %}{{ CONFIG.favicon.url }}{% else %}/static/assets/img/favicon.ico{% endif %}">
	<title>{% block title %}{% trans "Home" %}{% endblock title %} | {% trans "Exchange Crypto Currency" %}</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
	<meta http-equiv="description" name="description" content="{{ CONFIG.meta_description }}">
	<meta http-equiv="keywords" name="keywords" content="{{ CONFIG.meta_keywords }}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="all,follow">
	<link rel="stylesheet" type="text/css" href="/static/assets/css/base.css">
	{% block extracss %}{% endblock extracss %}
</head>
<body class="fixed-nav sticky-footer" id="page-top">
{% block content %}{% endblock content %}
<script type="text/javascript" src="/static/assets/libs/jq/jquery.min.js"></script>
<script type="text/javascript" src="/static/assets/libs/bs4/js/popper.min.js"></script>
<script type="text/javascript" src="/static/assets/libs/bs4/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/assets/libs/jquery-easing/jquery.easing.min.js"></script>
<script type="text/javascript" src="/static/assets/libs/sb-admin/js/sb-admin.min.js"></script>
{% block extrajs %}{% endblock extrajs %}
</body>
</html>

main/web/templates/web/content/home.html
{% extends "web/base.html" %}
{% load i18n staticfiles %}
{% block title %}{% trans "Home" %}{% endblock title %}
{% block extracss %}
<style type="text/css">
.form-control {width:100% !important;}
</style>
{% endblock extracss %}
{% block content %}
{% include "web/includes/sidebar.html" %}
<div class="content-wrapper">
	<div class="container-fluid">
		<h3><i class="fa fa-fw fa-podcast"></i> {% trans "Live Prices" %}</h3>
		<div class="row">
			<div class="form-group col-4">
				<label>{% trans "Limit" %}</label>&nbsp;&nbsp;
				<select class="form-control" id="limit_filter">
					<option>10</option><option>50</option><option selected>100</option><option>1000</option><option>10000</option>
				</select>
			</div>
			<div class="form-group col-4">
				<label>{% trans "Page" %}</label>&nbsp;&nbsp;
				<select class="form-control" id="start_filter">
					<option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option><option>7</option><option>8</option><option>9</option><option>10</option>
				</select>
			</div>
			<div class="form-group col-4">
				<label>{% trans "Search" %}</label>&nbsp;&nbsp;
				<input type="text" id="search_filter" class="form-control" placeholder="{% trans 'Search' %}">
			</div>
		</div>
		<table class="table table-stripped table-sm">
			<thead>
				<tr>
					<th>#</th>
					<th>{% trans "Name" %}</th>
					<th>{% trans "Market Cap" %}</th>
					<th>{% trans "Price" %}</th>
					<th>{% trans "Circulating Value" %}</th>
					<th>{% trans "Volume" %}</th>
					<th>%1h</th>
					<th>%24h</th>
					<th>%7d</th>
				</tr>
			</thead>
			<tbody id="trade_prices_list"></tbody>
		</table>
		<small>{% trans "Count" %} (<span id="trade_count">0</span>)</small>
	</div>
</div>
{% csrf_token %}
<input type="hidden" name="trade_prices_check" value="{% url 'web:trade_prices_check' %}">
{% endblock content %}
{% block extrajs %}
<script type="text/javascript">
window.main_trans = {
	"unknown": '{% trans "Unknown" %}',
}
</script>
<script type="text/javascript" src="/static/web/home.js"></script>
{% endblock extrajs %}

main/web/templates/web/includes/sidebar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg fixed-top bg-white" id="mainNav"><!-- navbar-dark bg-dark-->
  <a class="navbar-brand" href="{% url 'web:home_view' %}">
    <img src="/static/assets/img/logo.svg" alt="logo" style="width:30px;">
  </a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-dark bg-primary navbar-sidenav" id="exampleAccordion">
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="{% trans 'Live Price' %}">
        <a class="nav-link text-white" href="{% url 'web:home_view' %}">
          <i class="fa fa-fw fa-podcast"></i>
          <span class="nav-link-text">{% trans "Live Price" %}</span>
        </a>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
        <a class="nav-link text-white" href="#">
          <i class="fa fa-fw fa-chart-area"></i>
          <span class="nav-link-text">Charts</span>
        </a>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
        <a class="nav-link text-white" href="#">
          <i class="fa fa-fw fa-list"></i>
          <span class="nav-link-text">Tables</span>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-angle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-envelope"></i>
          <span class="d-lg-none">Messages
            <span class="badge badge-pill badge-primary">12 New</span>
          </span>
          <span class="indicator text-primary d-none d-lg-block">
            <i class="fa fa-circle"></i>
          </span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <h6 class="dropdown-header">New Messages:</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>David Miller</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>Jane Smith</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>John Doe</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item small" href="#">{% trans "View all messages" %}</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-fw fa-bell"></i>
          <span class="d-lg-none">Alerts
            <span class="badge badge-pill badge-warning">6 New</span>
          </span>
          <span class="indicator text-warning d-none d-lg-block">
            <i class="fa fa-fw fa-circle"></i>
          </span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <h6 class="dropdown-header">New Alerts:</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-success">
              <strong>
                <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-danger">
              <strong>
                <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-success">
              <strong>
                <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item small" href="#">View all alerts</a>
        </div>
      </li>
      <!--<li class="nav-item">
        <form class="form-inline my-2 my-lg-0 mr-lg-2">
          <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for...">
            <span class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fa fa-search"></i>
              </button>
            </span>
          </div>
        </form>
      </li>-->
      <li class="nav-item">
        <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
          <i class="fa fa-fw fa-sign-out"></i>{% trans "Logout" %}</a>
      </li>
    </ul>
  </div>
</nav>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% trans "Ready to Leave?" %}</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">{% trans "Select 'Logout' below if you are ready to end your current session." %}</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">{% trans "Cancel" %}</button>
        <a class="btn btn-primary" href="{% url 'web:logout_view' %}">{% trans "Logout" %}</a>
      </div>
    </div>
  </div>
</div>